builds:
    main: ./cmd/mpdbot/mpdbot.go
    env:
      - CGO_ENABLED=1
      
    goarch:
      - amd64
      - arm
      - arm64
archive:
  files:
    - LICENSE.txt
    - README.md
    - config.yml
